# Generated by Django 2.2.4 on 2019-08-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuaplicativo', '0002_auto_20190812_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clientenew',
            new_name='Cliente',
        ),
    ]
