# Generated by Django 2.2.4 on 2019-08-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuaplicativo', '0003_auto_20190812_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['criado_em'], 'verbose_name': 'nome', 'verbose_name_plural': 'nomes'},
        ),
    ]
