# Generated by Django 2.2.4 on 2019-08-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuaplicativo', '0004_auto_20190813_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={},
        ),
    ]
