# Generated by Django 2.2.4 on 2019-08-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuaplicativo', '0006_auto_20190813_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
